
---
{{- if .Values.flyteadmin.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "flyteadmin.name" . }}
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteadmin.labels" . | nindent 4 }}
  {{- with .Values.flyteadmin.serviceAccount.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.flyteadmin.serviceAccount.imagePullSecrets }}
imagePullSecrets: {{ toYaml . | nindent 2 }}
{{- end }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "flyteadmin.name" . }}
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteadmin.labels" . | nindent 4 }}
rules:
- apiGroups:
  - flyte.lyft.com
  resources:
  - flyteworkflows
#  - configmaps
#  - namespaces
#  - pods
#  - resourcequotas
#  - roles
#  - rolebindings
#  - secrets
#  - services
#  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "flyteadmin.name" . }}-binding
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteadmin.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "flyteadmin.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "flyteadmin.name" . }}
  namespace: {{ template "flyte.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "flyteadmin.name" . }}-10302-flytepoc-flytesnacks-dev-jpdev
  namespace: 10302-flytepoc-flytesnacks-dev-jpdev
  labels: {{ include "flyteadmin.labels" . | nindent 4 }}
rules:
- apiGroups:
  - flyte.lyft.com
  resources:
  - flyteworkflows
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "flyteadmin.name" . }}-10302-flytepoc-flytesnacks-dev-jpdev-binding
  namespace: 10302-flytepoc-flytesnacks-dev-jpdev
  labels: {{ include "flyteadmin.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "flyteadmin.name" . }}-10302-flytepoc-flytesnacks-dev-jpdev
subjects:
- kind: ServiceAccount
  name: {{ template "flyteadmin.name" . }}
  namespace: {{ template "flyte.namespace" . }}
