apiVersion: v2
name: flyte
description: A Helm chart for Flyte
type: application
version: 0.1.10 # VERSION
dependencies:
  - name: contour
    version: 4.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: contour.enabled
  - name: spark-operator
    alias: sparkoperator
    version: 1.0.6
    repository: https://googlecloudplatform.github.io/spark-on-k8s-operator
    condition: spark.enabled
  - name: kubernetes-dashboard
    version: 4.0.2
    repository: https://kubernetes.github.io/dashboard/
    condition: kubernetes-dashboard.enabled
  - name: postgresql
    version: 4.0.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: postgresql
    version: 8.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: minio
    version: 7.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled