# TODO update the storage configuration to match the storage.yaml. Keep the enable-multicontainer: true
kind: ConfigMap
apiVersion: v1
metadata:
  name: flyte-data-config
  namespace: {{ namespace }}
data:
  config.yaml: |
    storage:
      type: mem
      enable-multicontainer: true
