database:
  port: 5432
  username: flyte
  # TODO Change this to match aurora or rds postgres endpoint
  host: flyteadmin.cluster-cguibupmpitq.us-east-2.rds.amazonaws.com	
  dbname: flyteadmin
  passwordPath: /etc/db/pass.txt
