resources:
- deployment.yaml
- service.yaml

# Images that should be used
images:
  # FlyteAdmin
  - name: flyteadmin # match images with this name
    newTag: v0.3.5 # override the tag
    newName: docker.io/lyft/flyteadmin # override the name
