resources:
- rbac.yaml
- deployment.yaml
- service.yaml

# Images that should be used
images:
  # Flyte DataCatalog
  - name: datacatalog # match images with this name
    newTag: v0.2.2 # override the tag
    newName: docker.io/lyft/datacatalog # override the name
 
