apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/aws/amazon-sagemaker-operator-for-k8s/24853d92a8b2c282d62aafac06b8a0df5f138039/release/rolebased/installer.yaml