apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: syncresources
  namespace: flyte
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: flyteadmin
          containers:
          - name: sync-cluster-resources
            image: flyteadmin:v0.3.29
            imagePullPolicy: IfNotPresent
            command: ["flyteadmin", "--logtostderr", "--config", "/etc/flyte/config/*.yaml", "clusterresource", "sync"]
            volumeMounts:
            - name: resource-templates 
              mountPath: /etc/flyte/clusterresource/templates
            - name: config-volume
              mountPath: /etc/flyte/config
            - name: db-pass
              mountPath: /etc/db
          volumes:
          - name: resource-templates 
            configMap:
              name: clusterresource-template 
          - name: config-volume
            configMap:
              name: flyte-admin-config
          - name: db-pass
            secret:
              secretName: db-pass
          restartPolicy: OnFailure
