{{- if .Values.workflow_scheduler.enabled}}
  {{- if eq .Values.workflow_scheduler.type "native" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: flyte-scheduler-config
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flytescheduler.labels" . | nindent 4 }}
data:
{{- with .Values.configmap.admin }}
  admin.yaml: | {{ toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.db.admin }}
  db.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.configmap.logger }}
  logger.yaml: | {{ toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.configmap.adminServer }}
  server.yaml: | {{ toYaml . | nindent 4 }}
{{- end }}
  storage.yaml: | {{ tpl (include "storage" .) $ | nindent 4 }}
{{- if .Values.workflow_scheduler.enabled }}
{{- with .Values.workflow_scheduler.config }}
  scheduler.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- end }}
  {{- end }}
{{- end }}