apiVersion: apps/v1
kind: Deployment
metadata:
  name: flytepropeller
  namespace: flyte
spec:
  template:
    spec:
      containers:
        - name: flytepropeller
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
              ephemeral-storage: "1Gi"
