apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# All the resources that make up the deployment
resources:
# global resources
- ../namespace
- ../ingress
- ../admindeployment
- ../datacatalog
- ../console
- ../wf_crd
- ../propeller
- ../adminserviceaccount

##############################################
# Generate Configs
# For each component exactly one config is generated
# For every component required configs are
# 1. logger.yaml
# 2. storage.yaml
# 3. component.yaml
#
# db.yaml is required for FlyteAdmin and DataCatalog
# ############################################
configMapGenerator:
# the main admin configmap
- name: flyte-admin-config
  files:
    - ./config/admin/server.yaml
    - ./config/admin/db.yaml
    - ./config/admin/cluster_resources.yaml
    - ./config/admin/remote_data.yaml
    - ./config/admin/task_resource_defaults.yaml
    - ./config/storage.yaml
    - ./config/logger.yaml

# cluster resource templates
- name: clusterresource-template
  files:
# Files are read in alphabetical order. To ensure that we create the namespace first, prefix the file name with "aa".
    - ./config/clusterresource-templates/aa_namespace.yaml
    - ./config/clusterresource-templates/ab_project-resource-quota.yaml
    - ./config/clusterresource-templates/ac_project-copilot-dataconfig.yaml
    - ./config/clusterresource-templates/ad_spark-role.yaml
    - ./config/clusterresource-templates/ae_spark-service-account.yaml
    - ./config/clusterresource-templates/af_spark-role-binding.yaml

# Flyte Propeller Configuration
- name: flyte-propeller-config
  files:
    - ./config/propeller/core.yaml
    - ./config/propeller/admin.yaml
    - ./config/propeller/catalog.yaml
    - ./config/enabled_plugins.yaml
    - ./config/plugins/copilot.yaml
    - ./config/plugins/k8s.yaml
    - ./config/plugins/task_logs.yaml
    - ./config/storage.yaml
    - ./config/logger.yaml

# TODO Flyte Console Configuration
#- name: flyte-console-config
#  files:
#    - ./config/console.yaml

- name: datacatalog-config
  files:
    - ./config/datacatalog/server.yaml
    - ./config/datacatalog/db.yaml
    - ./config/storage.yaml
    - ./config/logger.yaml
