server:
  httpPort: 8088
  grpcPort: 8089
  security:
    secure: false
    useAuth: false
    allowCors: true
    allowedOrigins:
      # Accepting all domains for Sandbox installation
      - "*"
    allowedHeaders:
      - "Content-Type"
flyteadmin:
  roleNameKey: "iam.amazonaws.com/role"
