apiVersion: v1
kind: ServiceAccount
metadata:
  name: datacatalog
  namespace: flyte
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::590375264460:role/eksctl-flyte-addon-iamserviceaccount-flyte-f-Role1-F328POU8L7HT"
