datacatalog:
  storage-prefix: metadata/datacatalog
  metrics-scope: "datacatalog"
  profiler-port: 10254
application:
  grpcPort: 8089
# TODO lets move this to db.yaml, but the dbname is the problem currently
database:
  port: 5432
  username: postgres
  host: postgres
  dbname: datacatalog
  options: sslmode=disable
