name: Create a flyte release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version name. example v0.1.1'
        required: true

jobs:
  goreleaser:
    name: Bump new version of flyte
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"

      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.FLYTE_BOT_PAT }}
          WITH_V: true
          CUSTOM_TAG: ${{ github.event.inputs.version }}
          RELEASE_BRANCHES: master
