name: tests
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  end-to-end:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        go-version: [1.10]
    steps:
    - uses: actions/checkout@v1
    - name: Kustomize and diff
      run: DELTA_CHECK=true make kustomize
    - name: Set up Go@${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Run end-to-end tests
      run: make end2end
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create Release Notes
      uses: docker://decathlon/release-notes-generator-action:2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FOLDER: temp_release_notes
        USE_MILESTONE_TITLE: "true"

